### ISSUE TITLE
WSL docker-compose Error - maintain: restore: Get: Get: EOF

### ISSUE THREAD

**Issue by pdavis156879** [keratin/authn-server#167]
I'm using docker-compose two throw three docker instances:
- PostgreSQL + Redis are being instanced by a docker-compose yml
- Authn is being instanced on a standalone docker-compose

The first runs fine; however, when attempting to launch Authn's I get the following output:

```
Running migrations.
Migrations complete.
~*~ Keratin AuthN v1.10.2 ~*~
Maintain: restore: Get: Get: EOF
```

Any idea on this strange not very informative error?

Authn docker-compose YML:
```

version: '3.9'

services:
  auth-service:
    image: keratin/authn-server:1.10.2
    ports:
      - "7002:3000"
    volumes:
      - auth-data:/var/lib/auth-service/data 
    networks:
      - auth-network
    environment:
      - APP_DOMAINS=users.myapp.com
      - AUTHN_URL=http://host.docker.internal:8080
      - SECRET_KEY_BASE='super-secret'
      - DATABASE_URL=postgres://user:pwd@host.docker.internal:5432/db-name?sslmode=disable
      - REDIS_URL=redis://pwd@host.docker.internal:5000/11
      - HTTP_AUTH_USERNAME=hello
      - HTTP_AUTH_PASSWORD=world
      - USERNAME_IS_EMAIL=true
    command: /bin/sh -c "./authn migrate && ./authn server"

networks: 
  auth-network:

volumes:
  auth-data:
```
Databases' docker-compsoe YML:
```

version: '3.9'

services:
  postgres-main:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "pwd"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  redis-main:
    image: "redis:alpine"
    restart: always
    environment:
      REDIS_PASSWORD: "pwd"
    ports:
      - "5000:5000"
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - redis-network
    command: redis-server --requirepass $${REDIS_PASSWORD}

networks: 
  postgres-network:
  redis-network:

volumes:
  postgres-data:
  redis-data:
```
