### ISSUE TITLE
AuthN Docker RDS Connectivity Issue

### ISSUE THREAD

**Issue by xcskier56** [keratin/authn-server#175]
Hi there, I'm getting the following error when trying to run the AuthN docker image on EC2 Ubuntu 20.04. 

```
~*~ Keratin AuthN v1.10.4 ~*~
data.NewDB: dial tcp: lookup <redacted>.us-east-1.rds.amazonaws.com: device or resource busy
```

I have a fairly simple setup, just an EC2 instance and an RDS instance. I have done the following debugging and am quite certain that it is not a networking issue like security groups.
1. On the EC2, I can `psql` to the RDS instance
2. I used `docker exec` to run the AuthN container, installed psql using `apk --update add postgresql-client` and was able to successfully connect to rds
3. There is a dockerized Rails app on the same EC2 that can reach the same RDS instance
4. The docker-compose below works fine on my local machine (mac) but causes the above error on EC2

Here is my docker-compose (sensitive items removed)

```
version: '3.8'
volumes:
  redis_auth_data:

networks:
  frontend:
  backend:

services:
  redis:
    image: redis
    # using persistant storage
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_auth_data:/data
    networks:
      backend:
        aliases:
          - redis_auth.docker # used below

  keratin_auth:
    image: keratin/authn-server:1.10.4
    ports:
      - "21002:3000"
      - "21001:21001"
    environment:
      - AUTHN_URL=http://localhost:8080
      - APP_DOMAINS=localhost
      - HTTP_AUTH_USERNAME # passthrough from env
      - HTTP_AUTH_PASSWORD # passthrough from env
      - DATABASE_URL=postgresql://<pg_username>:<pg_password>@<host>.us-east-1.rds.amazonaws.com/keratin_authn
      - PUBLIC_PORT=21001
      - REDIS_URL=redis://redis_auth.docker:6379/1
      - SECRET_KEY_BASE=<redacted>
    networks:
      backend:
      frontend:
    depends_on:
      - redis
```

Thanks in advance

**Comment by cainlevy** [comment]
That's a new one!

A few options to consider:

- do you get a different error if the database url has the wrong host, port, or credentials?
- could you also try v1.10.3? I just updated the Postgres driver in v1.10.4, and while it's currently working for my own connection to RDS, testing the previous patch could eliminate a regression

**Comment by xcskier56** [comment]
@cainlevy,

1. I do not get a different error with an invalid postgres url
2. This is still occurring on 1.10.3. 

I have created a compose file that is reproducing the problem for me. This file works on my local machine (mac) but fails on EC2 with ubuntu 20.04 AND on an Azure VM running Ubuntu 18.04. I did some searching for Go + Docker connectivity and maybe saw something about Go using different DNS lookup like 8.8.8.8 so it couldn't resolve a non-public endpoint. Not sure if real and even related but an idea. Here's the docker-file that should reproduce the problem:

```
version: '3.9'

services:
  keratin_auth:
    image: keratin/authn-server:1.10.3
    ports:
      - 8080:3000
    environment:
      - AUTHN_URL=http://localhost:8080
      - APP_DOMAINS=localhost
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgres://postgres:password@postgres:5432/keratin_authn?sslmode=disable
      - SECRET_KEY_BASE=changeme
      - HTTP_AUTH_USERNAME=hello
      - HTTP_AUTH_PASSWORD=world
    networks:
      - my-network
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - /var/www/redis:/data
    networks:
      - my-network

  postgres:
    image: postgres:12.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keratin_authn
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/www/postgres:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge
```
