### ISSUE TITLE
sometimes periodically i got this error using docker-compose ` panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving`

### ISSUE THREAD

**Issue by katemicse** [keratin/authn-server#85]
```
Migrations complete.
authn_1      | 2018-12-02T07:26:10.992252404Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:26:10.992317137Z 
authn_1      | 2018-12-02T07:26:10.992322506Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:26:10.992368830Z main.serve()
authn_1      | 2018-12-02T07:26:10.992553187Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:26:10.992565421Z main.main()
authn_1      | 2018-12-02T07:26:10.992752471Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:27:12.460976560Z Running migrations.
authn_1      | 2018-12-02T07:27:12.463898632Z Migrations complete.
authn_1      | 2018-12-02T07:27:13.080815518Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:27:13.080892192Z 
authn_1      | 2018-12-02T07:27:13.080904512Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:27:13.080912089Z main.serve()
authn_1      | 2018-12-02T07:27:13.080959503Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:27:13.080969132Z main.main()
authn_1      | 2018-12-02T07:27:13.080975757Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:28:14.635789037Z Running migrations.
authn_1      | 2018-12-02T07:28:14.638045908Z Migrations complete.
authn_1      | 2018-12-02T07:28:15.250106811Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:28:15.250230990Z 
authn_1      | 2018-12-02T07:28:15.250592945Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:28:15.250794379Z main.serve()
authn_1      | 2018-12-02T07:28:15.251195918Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:28:15.251368486Z main.main()
authn_1      | 2018-12-02T07:28:15.251794639Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:29:16.770222793Z Running migrations.
authn_1      | 2018-12-02T07:29:16.772268855Z Migrations complete.
authn_1      | 2018-12-02T07:29:17.384239561Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:29:17.384294914Z 
authn_1      | 2018-12-02T07:29:17.384300124Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:29:17.384304114Z main.serve()
authn_1      | 2018-12-02T07:29:17.384308195Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:29:17.384312832Z main.main()
authn_1      | 2018-12-02T07:29:17.384316733Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:30:18.854866098Z Running migrations.
authn_1      | 2018-12-02T07:30:18.856587725Z Migrations complete.
authn_1      | 2018-12-02T07:30:19.421116249Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:30:19.421162510Z 
authn_1      | 2018-12-02T07:30:19.421169742Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:30:19.421175026Z main.serve()
authn_1      | 2018-12-02T07:30:19.421180097Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:30:19.421185520Z main.main()
authn_1      | 2018-12-02T07:30:19.421190489Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:31:20.835637674Z Running migrations.
authn_1      | 2018-12-02T07:31:20.838071799Z Migrations complete.
authn_1      | 2018-12-02T07:31:21.377716984Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:31:21.377753726Z 
authn_1      | 2018-12-02T07:31:21.377758873Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:31:21.377763222Z main.serve()
authn_1      | 2018-12-02T07:31:21.377767252Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:31:21.377771721Z main.main()
authn_1      | 2018-12-02T07:31:21.377775612Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:32:22.842250830Z Running migrations.
authn_1      | 2018-12-02T07:32:22.844296017Z Migrations complete.
authn_1      | 2018-12-02T07:32:23.415242364Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:32:23.415393516Z 
authn_1      | 2018-12-02T07:32:23.415941427Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:32:23.416267274Z main.serve()
authn_1      | 2018-12-02T07:32:23.417003084Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:32:23.417462929Z main.main()
authn_1      | 2018-12-02T07:32:23.418244505Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
authn_1      | 2018-12-02T07:33:24.878422344Z Running migrations.
authn_1      | 2018-12-02T07:33:24.880465989Z Migrations complete.
authn_1      | 2018-12-02T07:33:25.504215637Z panic: Maintain: restore: Get: Get: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving
authn_1      | 2018-12-02T07:33:25.504249889Z 
authn_1      | 2018-12-02T07:33:25.504258351Z goroutine 1 [running]:
authn_1      | 2018-12-02T07:33:25.504265573Z main.serve()
authn_1      | 2018-12-02T07:33:25.504272502Z 	/go/src/github.com/keratin/authn-server/main.go:40 +0x49b
authn_1      | 2018-12-02T07:33:25.504279994Z main.main()
authn_1      | 2018-12-02T07:33:25.504286822Z 	/go/src/github.com/keratin/authn-server/main.go:26 +0xfb
```

**Comment by cainlevy** [comment]
Would you include your docker-compose.yml? I'm curious how you've defined Redis and AuthN.

**Comment by katemicse** [comment]
@cainlevy 
```
  db:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: authn

    volumes:
       - db_data:/var/lib/mysql

  redis:
    image: redis
  authn:
    image: keratin/authn-server:1.4.1
    command: sh -c "./authn migrate && ./authn server"
    restart: always
    ports:
      - "8765:3000"
    expose:
      - "3000"
    links:
      - db
    environment:
      PASSWORD_POLICY_SCORE: 0
      HTTP_AUTH_USERNAME: authname
      HTTP_AUTH_PASSWORD: 123456
      USERNAME_IS_EMAIL: "yes"
      DATABASE_URL: mysql://root:qwerty@db:3306/authn
      REDIS_URL: redis://redis:6379/0
      AUTHN_URL: http://authn:3000
      APP_DOMAINS: localhost
      SECRET_KEY_BASE: qwerty12345
      APP_PASSWORD_RESET_URL: http://api:5000/authn/resetpass
    depends_on:
      - redis
      - db

```
